// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjNxFBWXWgcCn5WrCfW7ptCzq9kQGqlfM',
    appId: '1:142390867095:web:78bfe6f03c0eba137365d2',
    messagingSenderId: '142390867095',
    projectId: 'car-rental-app-aj',
    authDomain: 'car-rental-app-aj.firebaseapp.com',
    storageBucket: 'car-rental-app-aj.appspot.com',
    measurementId: 'G-4KL0ZL04GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGTfEq1Jpnrxwh7t43EHasKwVhZsuGzN4',
    appId: '1:142390867095:android:82614d5bdbc84ee67365d2',
    messagingSenderId: '142390867095',
    projectId: 'car-rental-app-aj',
    storageBucket: 'car-rental-app-aj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG4rXNka0kBbHEMT2es7Yo49W0vVOKPpU',
    appId: '1:142390867095:ios:7af6d2f6b0724d737365d2',
    messagingSenderId: '142390867095',
    projectId: 'car-rental-app-aj',
    storageBucket: 'car-rental-app-aj.appspot.com',
    iosBundleId: 'com.example.carrentalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG4rXNka0kBbHEMT2es7Yo49W0vVOKPpU',
    appId: '1:142390867095:ios:7af6d2f6b0724d737365d2',
    messagingSenderId: '142390867095',
    projectId: 'car-rental-app-aj',
    storageBucket: 'car-rental-app-aj.appspot.com',
    iosBundleId: 'com.example.carrentalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjNxFBWXWgcCn5WrCfW7ptCzq9kQGqlfM',
    appId: '1:142390867095:web:1a33719ca47d6a4c7365d2',
    messagingSenderId: '142390867095',
    projectId: 'car-rental-app-aj',
    authDomain: 'car-rental-app-aj.firebaseapp.com',
    storageBucket: 'car-rental-app-aj.appspot.com',
    measurementId: 'G-D50JK6ECX3',
  );
}
